version: "3.8"
services:
  postgresdb:
    container_name: postgres
    image: postgres:alpine
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME

  api:
    container_name: backend-host
    restart: always
    build:
      context: ./server/
      dockerfile: Dockerfile
    image:  file-viewer-backend
    ports:
      - $SERVER_PORT:$SERVER_PORT
    environment:
      - SERVER_PORT=$SERVER_PORT
      - CLIENT_HOST_URL=$CLIENT_HOST_URL
      - DB_USER=$DB_USER
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=$DB_PORT
    depends_on:
      - postgresdb
    volumes:
      - ./uploads:/usr/server/uploads

  react:
    container_name: frontend-host
    build:
      context: ./client/
      dockerfile: Dockerfile
    image: file-viewer-frontend
    ports:
      - $CLIENT_PORT:$CLIENT_PORT
    environment:
      - PORT=$CLIENT_PORT
      - CLIENT_PORT=$CLIENT_PORT
      - NEXT_PUBLIC_CLIENT_HOST_URL=$NEXT_PUBLIC_CLIENT_HOST_URL
      - NEXT_PUBLIC_SERVER_HOST_URL=$NEXT_PUBLIC_SERVER_HOST_URL

volumes:
  data: {}
